### ISSUE TITLE
12040 and 12041 needs Special Judge

### ISSUE THREAD

**Issue by BupjaeLee** [Startlink/BOJ-spj#41]
https://www.acmicpc.net/problem/12040
https://www.acmicpc.net/problem/12041

The problem says:

For each of the non-IMPOSSIBLE cases, the sample output shows only one possible answer. There are many valid answers for these inputs.

**Comment by Baekjoon** [comment]
README.md 에 이미 추가되어 있으니, 언젠간 추가될 것으로 예상됩니다.
